import { Pool } from "pg";
import { DsqlSigner } from "@aws-sdk/dsql-signer";
import { awsCredentialsProvider } from "@vercel/functions/oidc";
import {
  nodeDigest, validatePublication, verifyRestoredVault,
  type CatalogLimits, type CatalogStore, type CatalogRestoreSource, type PublishResult,
  type PublishReceipt, type ValidatedPublication, type RestoreLimits, type RestoreResult,
  type RawRestoredEntry,
} from "../wiki/catalog-contract";
import { objectKeyFor, putImmutable, readVerified, type ObjectStore } from "./object-store";

/** Injectable wire boundary. All transaction statements run on one leased client. */
export interface NodeDsqlClient {
  query(text: string, values?: unknown[]): Promise<{ rows: Record<string, unknown>[] }>;
  release(destroy?: boolean): void;
}
export interface NodeDsqlPool {
  connect(): Promise<NodeDsqlClient>;
  end(): Promise<void>;
}
export interface NodeDsqlConnection {
  host: string;
  region: string;
  roleArn: string;
  user: string;
  maxConnections: number;
  connectionTimeoutMillis: number;
  idleTimeoutMillis: number;
  maxLifetimeSeconds: number;
  queryTimeoutMillis: number;
}
export interface NodeDsqlOptions {
  schema: string;
  objects: ObjectStore;
  limits: CatalogLimits;
  restoreLimits: RestoreLimits;
  metadataLimits: { maxPathBytes: number; maxContentTypeBytes: number; maxReceiptBytes: number };
  connection?: NodeDsqlConnection;
  /** Local tests may inject a pool; its caller owns transport configuration. */
  pool?: NodeDsqlPool;
  maxAttempts: number;
  retryBackoffMs: number;
}
export interface NodeDsqlMetrics {
  sqlStatements: number;
  transactions: number;
  retries: number;
  retryExhaustions: number;
  failures: number;
  authFailures: number;
  poolErrors: number;
  tokensGenerated: number;
  restoredBytes: number;
}
const idPattern = /^[A-Za-z0-9][A-Za-z0-9_.-]{0,127}$/;
const addressPattern = /^[0-9a-f]{64}$/;
const utf8 = new TextEncoder();
const size = (s: string): number => Buffer.byteLength(s, "utf8");
const positive = (value: number, maximum = Number.MAX_SAFE_INTEGER): boolean => Number.isSafeInteger(value) && value > 0 && value <= maximum;
const failure = (): PublishResult => ({ status: "store-failed" });
const stateOf = (error: unknown): string => typeof error === "object" && error !== null && "code" in error && typeof error.code === "string" ? error.code : "";
const retryable = (error: unknown): boolean => ["40001", "23505", "28P01", "28000"].includes(stateOf(error));

/** Fresh IAM material is generated by pg for each new physical connection. */
export function nodeDsqlPoolConfig(connection: NodeDsqlConnection, metrics: NodeDsqlMetrics) {
  if (!connection.host.endsWith(`.dsql.${connection.region}.on.aws`) || !/^[a-z][a-z0-9-]+$/.test(connection.region)
    || !/^arn:aws:iam::\d{12}:role\/.+/.test(connection.roleArn)
    || !/^[a-z_][a-z0-9_]{0,62}$/.test(connection.user) || connection.user === "admin"
    || !positive(connection.maxConnections, 2) || !positive(connection.maxLifetimeSeconds, 3_000)
    || !positive(connection.connectionTimeoutMillis, 30_000) || !positive(connection.idleTimeoutMillis, 60_000)
    || !positive(connection.queryTimeoutMillis, 60_000)) throw new Error("Invalid bounded DSQL connection configuration");
  return {
    host: connection.host, port: 5432, database: "postgres", user: connection.user,
    ssl: { rejectUnauthorized: true }, max: connection.maxConnections,
    connectionTimeoutMillis: connection.connectionTimeoutMillis,
    idleTimeoutMillis: connection.idleTimeoutMillis, maxLifetimeSeconds: connection.maxLifetimeSeconds,
    query_timeout: connection.queryTimeoutMillis,
    application_name: "geode-node-catalog",
    password: async () => {
      let timeout: ReturnType<typeof setTimeout> | undefined;
      try {
        const signer = new DsqlSigner({ hostname: connection.host, region: connection.region,
          credentials: awsCredentialsProvider({ roleArn: connection.roleArn }), expiresIn: 900 });
        const token = await Promise.race([signer.getDbConnectAuthToken(),new Promise<never>((_,reject)=>{
          timeout=setTimeout(()=>reject(new Error("Credential timeout")),connection.connectionTimeoutMillis);
        })]);
        metrics.tokensGenerated += 1;
        return token;
      } catch {
        metrics.authFailures += 1;
        throw Object.assign(new Error("DSQL credential acquisition failed"), { code: "28000" });
      } finally { if(timeout!==undefined) clearTimeout(timeout); }
    },
  };
}

/** Node-only runtime adapter. No schema creation, admin access, or arbitrary-SQL API. */
export function createNodeDsqlCatalog(options: NodeDsqlOptions) {
  if (!/^[a-z_][a-z0-9_]{0,62}$/.test(options.schema) || ["public", "sys", "information_schema"].includes(options.schema) || options.schema.startsWith("pg_")) throw new Error("Invalid catalog schema");
  const limits = { ...options.limits, allowedContentTypes: [...options.limits.allowedContentTypes] };
  const restoreLimits = { ...options.restoreLimits, allowedContentTypes: [...options.restoreLimits.allowedContentTypes] };
  const metadata = { ...options.metadataLimits };
  const objects = options.objects;
  const maxAttempts = options.maxAttempts;
  const retryBackoffMs = options.retryBackoffMs;
  for (const limit of [limits.maxNoteBytes, limits.maxAssetBytes, limits.maxPublicationBytes, restoreLimits.maxNoteBytes, restoreLimits.maxAssetBytes, restoreLimits.maxVaultBytes]) if (!positive(limit)) throw new Error("Invalid byte limit");
  if (!positive(limits.maxPublicationEntries, 500) || !positive(restoreLimits.maxEntries, 10_000)
    || !positive(metadata.maxPathBytes, 4_096) || !positive(metadata.maxContentTypeBytes, 256)
    || !positive(metadata.maxReceiptBytes, 16_384) || !positive(options.maxAttempts, 10)
    || !Number.isSafeInteger(options.retryBackoffMs) || options.retryBackoffMs < 0 || options.retryBackoffMs > 1_000
    || Boolean(options.pool) === Boolean(options.connection)) throw new Error("Invalid bounded catalog options");
  const metrics: NodeDsqlMetrics = {sqlStatements:0,transactions:0,retries:0,retryExhaustions:0,failures:0,authFailures:0,poolErrors:0,tokensGenerated:0,restoredBytes:0};
  let pool: NodeDsqlPool;
  if (options.pool) pool = options.pool;
  else {
    const driver = new Pool(nodeDsqlPoolConfig(options.connection!, metrics));
    driver.on("error", () => { metrics.poolErrors += 1; });
    pool = driver;
  }
  let closed = false;
  let closing: Promise<void> | undefined;
  const pending = new Set<Promise<unknown>>();
  function track<T>(run: () => Promise<T>): Promise<T> {
    const operation=run();
    pending.add(operation);
    void operation.then(()=>pending.delete(operation),()=>pending.delete(operation));
    return operation;
  }
  const schema = `"${options.schema}"`;
  const bounded = (column: string, parameter: string): string => `CASE WHEN octet_length(${column}) <= ${parameter} THEN ${column} ELSE NULL END`;
  async function query(client: NodeDsqlClient, text: string, values: unknown[] = []) {
    if (closed) throw new Error("Catalog closed");
    metrics.sqlStatements += 1;
    return (await client.query(text, values)).rows;
  }
  async function transaction<T>(run: (client: NodeDsqlClient) => Promise<T>): Promise<T> {
    if (closed) throw new Error("Catalog closed");
    const client = await pool.connect();
    let destroy = false;
    try {
      metrics.transactions += 1;
      await query(client, "BEGIN ISOLATION LEVEL REPEATABLE READ");
      const result = await run(client);
      await query(client, "COMMIT");
      return result;
    } catch (error) {
      // A timed-out pg query can still be in flight. Discard rather than return
      // its connection to the pool, including if rollback itself fails.
      destroy = true;
      try { metrics.sqlStatements += 1; await client.query("ROLLBACK"); } catch { /* connection is discarded below */ }
      throw error;
    } finally { client.release(destroy); }
  }
  async function insert(client: NodeDsqlClient, table: "object" | "catalog_entry", columns: string, rows: unknown[][]) {
    if(!rows.length) return;
    const values: unknown[]=[];
    const tuples=rows.map(row=>`(${row.map(value=>{values.push(value);return `$${values.length}`;}).join(",")})`).join(",");
    await query(client,`INSERT INTO ${schema}.${table} (${columns}) VALUES ${tuples}`,values);
  }
  function receiptFor(p: ValidatedPublication): PublishReceipt {
    return {vaultId:p.vaultId, mutationId:p.mutationId, sequence:p.baseSequence+1, digest:p.digest, noteCount:p.notes.length, assetCount:p.assets.length};
  }
  async function check(client: NodeDsqlClient, p: ValidatedPublication): Promise<PublishResult | null> {
    const receipts = await query(client, `SELECT ${bounded("digest", "$3")} AS digest, ${bounded("receipt", "$4")} AS receipt FROM ${schema}.receipt WHERE vault_id=$1 AND mutation_id=$2 LIMIT 1`, [p.vaultId,p.mutationId,64,metadata.maxReceiptBytes]);
    if (receipts.length) {
      const row = receipts[0];
      if (row.digest !== p.digest) return {status:"mutation-id-reused"};
      if (typeof row.receipt !== "string") return failure();
      try {
        const stored: unknown = JSON.parse(row.receipt);
        const expected=receiptFor(p);
        if (!stored || typeof stored!=="object" || Object.entries(expected).some(([k,v]) => (stored as Record<string,unknown>)[k]!==v)) return failure();
        return {status:"ok",receipt:expected};
      } catch { return failure(); }
    }
    const rows = await query(client, `SELECT coalesce(max(sequence),0) AS sequence FROM ${schema}.vault_sequence WHERE vault_id=$1`, [p.vaultId]);
    const sequence=Number(rows[0]?.sequence);
    if (!Number.isSafeInteger(sequence) || sequence<0) return failure();
    return sequence===p.baseSequence ? null : {status:"conflict"};
  }
  const store: CatalogStore = { async commit(input) {
    // Reapply this adapter's explicit policy: a validated publication may have
    // been validated against different limits. Copy bytes before the first await.
    if (closed) return failure();
    const validation=validatePublication(input,{limits});
    if (validation.status!=="ok") return validation;
    if (validation.publication.digest!==input.digest || input.baseSequence>=Number.MAX_SAFE_INTEGER) return failure();
    const p={...validation.publication,notes:validation.publication.notes.map(n=>({...n})),assets:validation.publication.assets.map(a=>({...a,bytes:a.bytes.slice()}))};
    if(size(JSON.stringify(receiptFor(p)))>metadata.maxReceiptBytes) return failure();
    if ([...p.notes,...p.assets].some(e=>size(e.path)>metadata.maxPathBytes)) return {status:"invalid-path"};
    if (p.assets.some(a=>size(a.contentType)>metadata.maxContentTypeBytes)) return {status:"unsupported-content-type"};
    const entries=[...p.notes.map(n=>({path:n.path,kind:"note",bytes:utf8.encode(n.text),contentType:"text/markdown"})),...p.assets.map(a=>({path:a.path,kind:"attachment",bytes:a.bytes,contentType:a.contentType}))].map(e=>({...e,address:nodeDigest.sha256Hex(e.bytes)}));
    const needed=new Map(entries.map(e=>[e.address,e]));
    let uploaded=false;
    for (let attempt=1;attempt<=maxAttempts;attempt++) {
      try {
        if (!uploaded) {
          const early=await transaction(client=>check(client,p));
          if (early) return early;
          // Never keep a database transaction open during object-store I/O.
          for (const e of needed.values()) {
            if (closed) return failure();
            const key=objectKeyFor(p.vaultId,e.address);
            const result=await putImmutable(objects,key,e.bytes,e.contentType,e.address);
            if (result.status!=="ok") return result;
            if (result.key!==key) return failure();
          }
          uploaded=true;
        }
        return await transaction(async client => {
          const early=await check(client,p);
          if (early) return early;
          const existing=await query(client,`SELECT content_address, byte_length, ${bounded("object_key","$3")} AS object_key FROM ${schema}.object WHERE vault_id=$1 AND content_address = ANY($2::text[]) LIMIT $4`,[p.vaultId,[...needed.keys()],256,needed.size+1]);
          const recorded=new Map(existing.map(e=>[e.content_address,e]));
          for (const [address,e] of needed) {
            const row=recorded.get(address);
            if (row && (Number(row.byte_length)!==e.bytes.byteLength || row.object_key!==objectKeyFor(p.vaultId,address))) return {status:"duplicate-with-mismatched-bytes"};
          }
          await query(client,`INSERT INTO ${schema}.vault_sequence (vault_id,sequence,mutation_id) VALUES ($1,$2,$3)`,[p.vaultId,p.baseSequence+1,p.mutationId]);
          await insert(client,"object","vault_id,content_address,content_type,byte_length,object_key",[...needed].filter(([address])=>!recorded.has(address)).map(([address,e])=>[p.vaultId,address,e.contentType,e.bytes.byteLength,objectKeyFor(p.vaultId,address)]));
          await query(client,`DELETE FROM ${schema}.catalog_entry WHERE vault_id=$1 AND path = ANY($2::text[])`,[p.vaultId,entries.map(e=>e.path)]);
          await insert(client,"catalog_entry","vault_id,path,kind,content_address,content_type,sequence",entries.map(e=>[p.vaultId,e.path,e.kind,e.address,e.contentType,p.baseSequence+1]));
          const receipt=receiptFor(p);
          await query(client,`INSERT INTO ${schema}.receipt (vault_id,mutation_id,digest,receipt) VALUES ($1,$2,$3,$4)`,[p.vaultId,p.mutationId,p.digest,JSON.stringify(receipt)]);
          return {status:"ok",receipt};
        });
      } catch(error) {
        if (["28000","28P01"].includes(stateOf(error))) metrics.authFailures+=1;
        if (retryable(error)) {
          if (attempt<maxAttempts) {
            metrics.retries+=1;
            await new Promise<void>(done=>setTimeout(done,Math.round(retryBackoffMs*attempt*(0.5+Math.random()))));
            continue;
          }
          metrics.retryExhaustions+=1;
        }
        metrics.failures+=1;
        return failure();
      }
    }
    return failure();
  }};
  const source: CatalogRestoreSource = { async restore(vaultId): Promise<RestoreResult> {
    if (!idPattern.test(vaultId)) return {status:"invalid-vault-id"};
    try {
      const snapshot=await transaction(async client=>{
        const seq=await query(client,`SELECT coalesce(max(sequence),0) AS sequence FROM ${schema}.vault_sequence WHERE vault_id=$1`,[vaultId]);
        const rows=await query(client,`SELECT ${bounded("e.path","$2")} AS path, ${bounded("e.kind","$3")} AS kind, ${bounded("e.content_address","$4")} AS content_address, ${bounded("e.content_type","$5")} AS content_type, o.byte_length, ${bounded("o.object_key","$6")} AS object_key FROM ${schema}.catalog_entry e LEFT JOIN ${schema}.object o ON o.vault_id=e.vault_id AND o.content_address=e.content_address WHERE e.vault_id=$1 ORDER BY e.path LIMIT $7`,[vaultId,metadata.maxPathBytes,10,64,metadata.maxContentTypeBytes,256,restoreLimits.maxEntries+1]);
        return {sequence:Number(seq[0]?.sequence),rows};
      });
      if (!snapshot.rows.length) return {status:"absent"};
      if (!Number.isSafeInteger(snapshot.sequence) || snapshot.sequence<1) return {status:"invalid-sequence"};
      if (snapshot.rows.length>restoreLimits.maxEntries) return {status:"entry-limit",observed:snapshot.rows.length,allowed:restoreLimits.maxEntries};
      // Reuse portable path/kind/collision checks with empty placeholder bytes.
      // Actual addresses and lengths are checked below, before byte hydration.
      const empty=new Uint8Array();
      const shape=verifyRestoredVault({vaultId,sequence:snapshot.sequence,entries:snapshot.rows.map(row=>({path:typeof row.path==="string"?row.path:"",kind:typeof row.kind==="string"?row.kind:"",text:"",bytes:empty,byteLength:0,contentAddress:nodeDigest.sha256Hex(empty),contentType:typeof row.content_type==="string"?row.content_type:null}))},{limits:restoreLimits});
      if(shape.status!=="ok") return shape;
      let total=0;
      // Check every metadata row before any object read; a later hostile row
      // must not trigger an expensive partial restore.
      for (const row of snapshot.rows) {
        if (typeof row.path!=="string" || size(row.path)>metadata.maxPathBytes) return {status:"invalid-path"};
        if (row.kind!=="note" && row.kind!=="attachment") return {status:"unknown-entry-kind",path:row.path};
        if (typeof row.content_address!=="string" || !addressPattern.test(row.content_address)) return {status:"invalid-content-address",path:row.path};
        if (row.object_key===null || row.byte_length===null) return {status:"missing-object",path:row.path};
        if (row.object_key!==objectKeyFor(vaultId,row.content_address)) return {status:"invalid-content-address",path:row.path};
        if (typeof row.content_type!=="string" || size(row.content_type)>metadata.maxContentTypeBytes) return {status:"incomplete-entry",path:row.path};
        if (row.kind==="attachment" && !restoreLimits.allowedContentTypes.includes(row.content_type)) return {status:"unsupported-content-type",path:row.path};
        const length=Number(row.byte_length), allowed=row.kind==="note"?restoreLimits.maxNoteBytes:restoreLimits.maxAssetBytes;
        if (!Number.isSafeInteger(length) || length<0) return {status:"byte-length-mismatch",path:row.path};
        if (length>allowed) return {status:"oversize",limit:row.kind==="note"?"note-bytes":"asset-bytes",observed:length,allowed};
        total+=length;
        if (!Number.isSafeInteger(total) || total>restoreLimits.maxVaultBytes) return {status:"oversize",limit:"vault-bytes",observed:total,allowed:restoreLimits.maxVaultBytes};
      }
      const entries: RawRestoredEntry[]=[];
      let actualTotal=0;
      for (const row of snapshot.rows) {
        if (closed) return {status:"store-failed"};
        const path=row.path as string, address=row.content_address as string;
        const read=await readVerified(objects,row.object_key as string,address);
        if (read.status!=="ok") return {status:read.status==="absent"?"missing-object":read.status==="address-mismatch"?"invalid-content-address":"store-failed",path};
        if (read.bytes.byteLength!==Number(row.byte_length)) return {status:"byte-length-mismatch",path};
        actualTotal+=read.bytes.byteLength;
        if (actualTotal>restoreLimits.maxVaultBytes) return {status:"oversize",limit:"vault-bytes",observed:actualTotal,allowed:restoreLimits.maxVaultBytes};
        metrics.restoredBytes+=read.bytes.byteLength;
        let text: string|null=null;
        if (row.kind==="note") {
          // A BOM is content in a note, not a transport header to discard.
          try { text=new TextDecoder("utf-8",{fatal:true,ignoreBOM:true}).decode(read.bytes); } catch { return {status:"incomplete-entry",path}; }
        }
        entries.push({path,kind:row.kind as string,text,contentAddress:address,contentType:row.content_type as string,byteLength:Number(row.byte_length),bytes:row.kind==="note"?null:read.bytes});
      }
      return verifyRestoredVault({vaultId,sequence:snapshot.sequence,entries},{limits:restoreLimits});
    } catch { metrics.failures+=1; return {status:"store-failed"}; }
  }};
  return {
    store: {commit:(publication:ValidatedPublication)=>track(()=>store.commit(publication))} satisfies CatalogStore,
    restoreSource:():CatalogRestoreSource=>({restore:(vaultId)=>track(()=>source.restore(vaultId))}),
    metrics:():Readonly<NodeDsqlMetrics>=>({...metrics}),
    close:():Promise<void>=>{
      closed=true;
      return closing??=(async()=>{await Promise.allSettled([...pending]);await pool.end();})();
    },
  };
}
