#!/usr/bin/env node
// Writes ios/version.xcconfig so the iOS MARKETING_VERSION tracks package.json.
// CURRENT_PROJECT_VERSION stays at its committed default unless IOS_BUILD_NUMBER
// is set (CI passes a monotonically increasing number per upload).
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const { version } = JSON.parse(readFileSync(`${root}package.json`, "utf8")) as { version: string };
const marketing = /^(\d+\.\d+\.\d+)/.exec(version)?.[1];
if (!marketing) throw new Error(`package.json version "${version}" is not x.y.z`);

const target = `${root}ios/version.xcconfig`;
const existing = readFileSync(target, "utf8");
const currentBuild = /^CURRENT_PROJECT_VERSION = (\d+)$/m.exec(existing)?.[1] ?? "1";
const build = process.env.IOS_BUILD_NUMBER ?? currentBuild;
if (!/^\d+$/.test(build)) throw new Error(`IOS_BUILD_NUMBER must be an integer, got "${build}"`);

writeFileSync(
  target,
  `// Generated by scripts/ios-version.mts (run by \`npm run ios:sync\`). MARKETING_VERSION tracks\n` +
    `// package.json; CURRENT_PROJECT_VERSION is the local default, CI overrides it per run.\n` +
    `MARKETING_VERSION = ${marketing}\nCURRENT_PROJECT_VERSION = ${build}\n`,
);
console.log(`ios/version.xcconfig: ${marketing} (${build})`);
